### ISSUE TITLE
WTFOS seems to be enabled but not active

### ISSUE THREAD

**Issue by StachowiakLukasz** [fpv-wtf/wtfos#71]
**Setup**:
Rooted DJI Googles V2 / firmware V01.06.0000 / wm170_gls (this mode is needed for o3 air unit)
O3 Air Unit / firmware V01.02.0000
Betaflight 4.4 with MSP Canvas mode OSD

**Problem**:
Not being able to see/use any of the available modules such as msp-osd or backgroud changing - ultimately only need OSD in DVR.

**History**:
Googles came in bundle with DJI FPV drone, firmware V01.01.0000. Immediately rooted and instaled WTFOS. Later updated firmware to V01.04.0000 and finally to V01.06.0000.
O3 Air unit Immediately updated to V01.02.0000

**Tried**:
https://github.com/fpv-wtf/wtfos/wiki/Troubleshooting
Reinstaled WTFOS multiple times
Sorted out the slots 1 & 2
/blackbox/wtfos.log & /blackbox/dinit.log does not output anything unordinary - services start normally 
Tried searching for similar issues without an avail

I'm aware that stock DJI Googles 2 are capable of recording DVR with OSD and V2's are not. Nevertheless I had little luck finding out wherther or not WTFOS will work properly with my setup.

**Comment by bri3d** [comment]
I think we chatted on Discord already, but the issue here is:

> O3 Air Unit

No WTFOS packages are currently designed to work with O3 Air Unit or FPV Drone Mode on Goggles V2. There's nothing stopping someone from making a package which augments O3 Air Unit mode - WTFOS is active and you still have root on the goggles. But, nobody has yet.
