### ISSUE TITLE
When updating can packages that have been updated be mentioned and possibly from and to version for them.

### ISSUE THREAD

**Issue by SilentZen** [fpv-wtf/wtfos#9]
When updating can packages that have been updated be mentioned and possibly from and to version for them.
Also seems like updates are not working DJI-OSD had to be removed and added in again via package manager to update.

**Comment by j005u** [comment]
You are right sir, we should show more details during the update. I opened an issue on the configurator repo for that: https://github.com/fpv-wtf/wtfos-configurator/issues/88

The problem with msp-osd stems from us having changed around how ground side and air side packages are managed and failing to account properly for the upgrade process. It shouldn't happen again with clean installs or if you do the uninstall/reinstall once manually. We'll do our best to avoid the situation in future.

Closing this issue here as nothing is to be done on wtfos itself.
